# config.yaml
# Centralized configuration settings for the AI word strategy game.
# Loaded at runtime to customize behavior without code changes.

game:
  min_word_length: 3
  max_word_length: 15
  initial_score: 0
  repeat_penalty_factor: 0.5  # Reduces score each time a word is reused

letter_pool:
  shared_letter_count: 4
  boggle_letter_count: 6
  min_vowels: 1
  min_consonants: 1
  common_letter_bias: true  # Heavily weight common letters (used in random sampling)

dictionary:
  filter_profanity: true
  min_dictionary_word_length: 3
  source: combined  # could be: nltk, wordfreq, or combined
