# config.yaml
# Centralized configuration settings for the AI word strategy game.
# This file is loaded at runtime to customize behavior without code changes.

game:
  min_word_length: 3            # Minimum valid word length
  max_word_length: 12           # Maximum valid word length
  initial_shared_letter_count: 4  # Number of shared letters (visible to both AI and player)
  initial_boggle_letter_count: 6  # Number of boggle letters (hidden from AI)
  max_turns: 100                # Optional: max turns per game to prevent infinite loops

scoring:
  base_score: 10                # Base score for a valid word
  length_multiplier: 2          # Score multiplier per letter in word
  penalty_repeat: 0.5           # Score penalty (as a multiplier) for reused words

letters:
  vowel_pool: ['A', 'E', 'I', 'O', 'U']
  consonant_pool: ['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z']
  shared_pool_size: 10          # Pool to draw shared letters from (ensures variation)
